<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList" epx="Concurrence"><NodeId>ArrayInLoop</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>success</Name>
        <Type>Boolean</Type>
        <InitialValue>
          <BooleanValue>true</BooleanValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><InvariantCondition><BooleanVariable>success</BooleanVariable></InvariantCondition><NodeBody><NodeList><Node NodeType="NodeList" epx="For"><NodeId>ep2cp_For_d1e33</NodeId><VariableDeclarations><DeclareVariable>
          <Name>i</Name>
          <Type>Integer</Type>
          <InitialValue>
            <IntegerValue>0</IntegerValue>
          </InitialValue>
        </DeclareVariable></VariableDeclarations><NodeBody><NodeList><Node NodeType="NodeList" epx="aux"><NodeId>ep2cp_ForLoop</NodeId><SkipCondition><NOT><LT><IntegerVariable>i</IntegerVariable><IntegerValue>3</IntegerValue></LT></NOT></SkipCondition><RepeatCondition><BooleanValue>true</BooleanValue></RepeatCondition><NodeBody><NodeList><Node NodeType="NodeList" epx="Try"><NodeId>A</NodeId><VariableDeclarations>
            <DeclareArray>
              <Name>array1</Name>
              <Type>Integer</Type>
              <MaxSize>5</MaxSize>
            </DeclareArray>
          </VariableDeclarations><EndCondition><OR><AND><EQInternal><NodeOutcomeVariable><NodeRef dir="child">BUG</NodeRef></NodeOutcomeVariable><NodeOutcomeValue>SUCCESS</NodeOutcomeValue></EQInternal><EQInternal><NodeStateVariable><NodeRef dir="child">BUG</NodeRef></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></AND><EQInternal><NodeStateVariable><NodeRef dir="child">plexilisp_Name_1</NodeRef></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></OR></EndCondition><PostCondition><OR><EQInternal><NodeOutcomeVariable><NodeRef dir="child">BUG</NodeRef></NodeOutcomeVariable><NodeOutcomeValue>SUCCESS</NodeOutcomeValue></EQInternal><EQInternal><NodeOutcomeVariable><NodeRef dir="child">plexilisp_Name_1</NodeRef></NodeOutcomeVariable><NodeOutcomeValue>SUCCESS</NodeOutcomeValue></EQInternal></OR></PostCondition><NodeBody><NodeList><Node NodeType="Assignment"><NodeId>BUG</NodeId><PreCondition><NOT><IsKnown><ArrayElement>
                    <Name>array1</Name>
                    <Index>
                      <IntegerValue>0</IntegerValue>
                    </Index>
                  </ArrayElement></IsKnown></NOT></PreCondition><NodeBody>
              <Assignment>
                <ArrayElement>
                  <Name>array1</Name>
                  <Index>
                    <IntegerValue>0</IntegerValue>
                  </Index>
                </ArrayElement>
                <NumericRHS>
                  <IntegerValue>1</IntegerValue>
                </NumericRHS>
              </Assignment>
            </NodeBody></Node><Node NodeType="Assignment"><NodeId>plexilisp_Name_1</NodeId><StartCondition><EQInternal><NodeStateVariable><NodeRef dir="sibling">BUG</NodeRef></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></StartCondition><NodeBody>
              <Assignment>
                <BooleanVariable>success</BooleanVariable>
                <BooleanRHS>
                  <BooleanValue>0</BooleanValue>
                </BooleanRHS>
              </Assignment>
            </NodeBody></Node></NodeList></NodeBody></Node><Node NodeType="Assignment" epx="LoopVariableUpdate"><NodeId>ep2cp_ForLoopUpdater</NodeId><StartCondition><EQInternal><NodeStateVariable><NodeRef dir="sibling">A</NodeRef></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></StartCondition><NodeBody><Assignment><IntegerVariable>i</IntegerVariable><NumericRHS><ADD>
          <IntegerVariable>i</IntegerVariable>
          <IntegerValue>1</IntegerValue>
        </ADD></NumericRHS></Assignment></NodeBody></Node></NodeList></NodeBody></Node></NodeList></NodeBody></Node></NodeList></NodeBody></Node></PlexilPlan>