<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Empty"><NodeId>boolean1</NodeId><PreCondition><LookupNow>
        <Name>
<StringValue>flag</StringValue>
        </Name>
      </LookupNow></PreCondition></Node></PlexilPlan>