<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Feb  7 19:41:00 2008 -->
<PlexilPlan>
<!-- Tests command with general expressions for arguments -->
  <Node NodeType="NodeList" >
    <NodeId>command5</NodeId>
    <NodeBody>
      <NodeList>
        <Node NodeType="Command" >
          <NodeId>StringCommand</NodeId>
          <NodeBody>
            <Command>
              <Name><StringValue>foo</StringValue></Name>
              <Arguments>
		<Concat>
		  <StringValue>Test</StringValue>
		  <StringValue>Arg</StringValue>
		</Concat>
              </Arguments>
            </Command>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
