<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>contention1</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>Integer</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <NodeList>
        <Node NodeType="NodeList"><NodeId>A</NodeId><NodeBody>
            <NodeList>
              <Node NodeType="Assignment"><NodeId>AA</NodeId><NodeBody>
                  <Assignment>
                    <IntegerVariable>foo</IntegerVariable>
                    <NumericRHS>
                      <IntegerValue>1</IntegerValue>
                    </NumericRHS>
                  </Assignment>
                </NodeBody></Node>
            </NodeList>
          </NodeBody></Node>
        <Node NodeType="NodeList"><NodeId>B</NodeId><StartCondition><EQInternal><NodeStateVariable><NodeId>A</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></StartCondition><NodeBody>
            <NodeList>
              <Node NodeType="Assignment"><NodeId>BB</NodeId><NodeBody>
                  <Assignment>
                    <IntegerVariable>foo</IntegerVariable>
                    <NumericRHS>
                      <IntegerValue>1</IntegerValue>
                    </NumericRHS>
                  </Assignment>
                </NodeBody></Node>
            </NodeList>
          </NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>