<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Mon Jun 18 15:09:57 2007 -->
<PlexilPlan>
  <!-- Illustrates a bug (?) in resource contention. This plan succeeds, as desired, but not if the list nodes wrapping A and B are removed. -->
  <Node NodeType="NodeList">
    <NodeId>contention3</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>Integer</Type>
      </DeclareVariable>
    </VariableDeclarations>
    <NodeBody>
      <NodeList>
              <Node NodeType="Assignment">
                <NodeId>AA</NodeId>
                <NodeBody>
                  <Assignment>
                    <IntegerVariable>foo</IntegerVariable>
                    <NumericRHS>
                      <IntegerValue>1</IntegerValue>
                    </NumericRHS>
                  </Assignment>
                </NodeBody>
              </Node>
              <Node NodeType="Assignment">
                <NodeId>BB</NodeId>
                <StartCondition>
                <EQInternal>
                 <NodeStateVariable>
                  <NodeId>AA</NodeId>
                 </NodeStateVariable>
                 <NodeStateValue>FINISHED</NodeStateValue>
                </EQInternal>
                </StartCondition>
                <NodeBody>
                  <Assignment>
                    <IntegerVariable>foo</IntegerVariable>
                    <NumericRHS>
                      <IntegerValue>2</IntegerValue>
                    </NumericRHS>
                  </Assignment>
                </NodeBody>
              </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
