<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan>
  <Node NodeType="NodeList">
    <NodeId>DoubleInvariantAssignment</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>x</Name>
        <Type>Boolean</Type>
        <InitialValue>
          <BooleanValue>0</BooleanValue>
        </InitialValue>
      </DeclareVariable>
      <DeclareVariable>
        <Name>y</Name>
        <Type>Boolean</Type>
        <InitialValue>
          <BooleanValue>0</BooleanValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
    <InvariantCondition>
      <EQBoolean>
	<BooleanVariable>x</BooleanVariable>
	<BooleanVariable>y</BooleanVariable>
      </EQBoolean>
    </InvariantCondition>
    <EndCondition>
      <AND>
	<EQInternal>
	  <NodeStateVariable>
	    <NodeId>Child1</NodeId>
	  </NodeStateVariable>
	  <NodeStateValue>FINISHED</NodeStateValue>
	</EQInternal>
	<EQInternal>
	  <NodeStateVariable>
	    <NodeId>Child2</NodeId>
	  </NodeStateVariable>
	  <NodeStateValue>FINISHED</NodeStateValue>
	</EQInternal>
      </AND>
    </EndCondition>
    <NodeBody>
      <NodeList>
	<Node NodeType="Assignment">
	  <NodeId>Child1</NodeId>
	  <Interface>
	    <InOut>
<!-- 	      <BooleanVariable>x</BooleanVariable> -->
              <DeclareVariable>
                <Name>x</Name>
                <Type>Boolean</Type>
                <InitialValue>
                  <BooleanValue>0</BooleanValue>
                </InitialValue>
              </DeclareVariable>
	    </InOut>
	  </Interface>
	  <NodeBody>
	    <Assignment>
	      <BooleanVariable>x</BooleanVariable>
	      <BooleanRHS>
		<BooleanValue>1</BooleanValue>
	      </BooleanRHS>
	    </Assignment>
	  </NodeBody>
	</Node>
	<Node NodeType="Assignment">
	  <NodeId>Child2</NodeId>
	  <Interface>
	    <InOut>
<!-- 	      <BooleanVariable>y</BooleanVariable> -->
              <DeclareVariable>
                <Name>y</Name>
                <Type>Boolean</Type>
                <InitialValue>
                  <BooleanValue>0</BooleanValue>
                </InitialValue>
              </DeclareVariable>
	    </InOut>
	  </Interface>
	  <NodeBody>
	    <Assignment>
	      <BooleanVariable>y</BooleanVariable>
	      <BooleanRHS>
		<BooleanValue>1</BooleanValue>
	      </BooleanRHS>
	    </Assignment>
	  </NodeBody>
	</Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
