<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>empty4</NodeId><EndCondition><EQInternal><NodeStateVariable><NodeId>foo</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></EndCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>foo</NodeId><StartCondition><BooleanValue>1</BooleanValue></StartCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>