<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>FailureType1</NodeId><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>One</NodeId><PostCondition><EQNumeric><IntegerValue>1</IntegerValue><IntegerValue>0</IntegerValue></EQNumeric></PostCondition></Node>
        <Node NodeType="Empty"><NodeId>Two</NodeId><EndCondition><AND><EQInternal><NodeStateVariable><NodeId>One</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal><EQInternal><NodeFailureVariable><NodeId>One</NodeId></NodeFailureVariable><NodeFailureValue>POST_CONDITION_FAILED</NodeFailureValue></EQInternal></AND></EndCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>