<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>FailureType3</NodeId><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>One</NodeId><PreCondition><EQNumeric><IntegerValue>1</IntegerValue><IntegerValue>0</IntegerValue></EQNumeric></PreCondition></Node>
        <Node NodeType="Empty"><NodeId>Two</NodeId><StartCondition><AND><EQInternal><NodeStateVariable><NodeId>One</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal><EQInternal><NodeFailureVariable><NodeId>One</NodeId></NodeFailureVariable><NodeFailureValue>PRE_CONDITION_FAILED</NodeFailureValue></EQInternal></AND></StartCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>