<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>isKnown1</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>test</Name>
        <Type>Boolean</Type>
      </DeclareVariable>
    </VariableDeclarations><PostCondition><IsKnown><NodeStateVariable>
          <NodeId>two</NodeId>
        </NodeStateVariable></IsKnown></PostCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>two</NodeId><StartCondition><IsKnown><BooleanVariable>test</BooleanVariable></IsKnown></StartCondition></Node>
        <Node NodeType="Assignment"><NodeId>one</NodeId><NodeBody>
            <Assignment>
              <BooleanVariable>test</BooleanVariable>
              <BooleanRHS>
                <BooleanValue>1</BooleanValue>
              </BooleanRHS>
            </Assignment>
          </NodeBody></Node>
        <Node NodeType="Empty"><NodeId>three</NodeId><StartCondition><IsKnown><NodeOutcomeVariable>
                <NodeId>two</NodeId>
              </NodeOutcomeVariable></IsKnown></StartCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>