<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Command"><NodeId>repeat7</NodeId><RepeatCondition><LookupOnChange>
        <Name>
<StringValue>continue</StringValue>
        </Name>
      </LookupOnChange></RepeatCondition><NodeBody>
      <Command>
        <Name>
<StringValue>foo</StringValue>
        </Name>
      </Command>
    </NodeBody></Node></PlexilPlan>