<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>repeat8</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>repeat-count</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><PostCondition><EQNumeric><IntegerValue>4</IntegerValue><IntegerVariable>repeat-count</IntegerVariable></EQNumeric></PostCondition><NodeBody>
      <NodeList>
        <Node NodeType="Assignment"><NodeId>repeater</NodeId><RepeatCondition><LookupOnChange>
              <Name>
<StringValue>continue</StringValue>
              </Name>
            </LookupOnChange></RepeatCondition><NodeBody>
            <Assignment>
              <IntegerVariable>repeat-count</IntegerVariable>
              <NumericRHS>
                <ADD>
                  <IntegerVariable>repeat-count</IntegerVariable>
                  <IntegerValue>1</IntegerValue>
                </ADD>
              </NumericRHS>
            </Assignment>
          </NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>