<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan>
  <GlobalDeclarations>
    <CommandDeclaration>
      <Name>drive</Name>
      <Return>
        <Type>Integer</Type>
      </Return>
    </CommandDeclaration>
    <CommandDeclaration>
      <Name>next_waypoint</Name>
    </CommandDeclaration>
  </GlobalDeclarations>
  <Node NodeType="NodeList">
    <NodeId>simple-closedloop-command-multipleAck</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>retTestFunction</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>-1</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
    <NodeBody>
      <NodeList>
        <Node NodeType="Command">
          <NodeId>Drive</NodeId>
          <EndCondition>
            <EQNumeric>
              <IntegerValue>10</IntegerValue>
              <IntegerVariable>retTestFunction</IntegerVariable>
            </EQNumeric>
          </EndCondition>
          <PostCondition>
            <EQInternal>
              <NodeCommandHandleVariable>
                <NodeId>Drive</NodeId>
              </NodeCommandHandleVariable>
              <NodeCommandHandleValue>COMMAND_SUCCESS</NodeCommandHandleValue>
            </EQInternal>
          </PostCondition>
          <NodeBody>
            <Command>
              <IntegerVariable>retTestFunction</IntegerVariable>
              <Name><StringValue>drive</StringValue></Name>
            </Command>
          </NodeBody>
        </Node>
        <Node NodeType="Command">
          <NodeId>NextWaypoint</NodeId>
          <StartCondition>
            <EQInternal>
              <NodeCommandHandleVariable>
                <NodeId>Drive</NodeId>
              </NodeCommandHandleVariable>
              <NodeCommandHandleValue>COMMAND_RCVD_BY_SYSTEM</NodeCommandHandleValue>
            </EQInternal>
          </StartCondition>
          <NodeBody>
            <Command>
              <Name><StringValue>next_waypoint</StringValue></Name>
            </Command>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
