<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://plexil.svn.sourceforge.net/viewvc/plexil/trunk/schema/core-plexil.xsd">
  <Node NodeType="NodeList">
    <NodeId>TestAbsSqrt</NodeId>
    <EndCondition>
      <AND>
	<EQInternal>
	  <NodeStateVariable><NodeId>SimpleAssignment1</NodeId></NodeStateVariable>
	  <NodeStateValue>FINISHED</NodeStateValue>
	</EQInternal>
	<EQInternal>
	  <NodeStateVariable><NodeId>SimpleAssignment2</NodeId></NodeStateVariable>
	  <NodeStateValue>FINISHED</NodeStateValue>
	</EQInternal>
      </AND>
    </EndCondition>
    <NodeBody>
      <NodeList>
	<Node NodeType="Assignment">
	  <NodeId>SimpleAssignment1</NodeId>
	  <VariableDeclarations>
	    <DeclareVariable>
              <Name>foo</Name>
              <Type>Integer</Type>
              <InitialValue>
                <IntegerValue>0</IntegerValue>
              </InitialValue>
            </DeclareVariable>
	  </VariableDeclarations>
	  <PreCondition>
	    <AND>
	      <LT>
		<SQRT>
		  <ADD>
		    <MUL>
		      <SUB>
			<RealValue>0.0</RealValue>
			<RealValue>0.0</RealValue>
		      </SUB>
		      <SUB>
			<RealValue>0.0</RealValue>
			<RealValue>0.0</RealValue>
		      </SUB>
		    </MUL>
		    <MUL>
		      <SUB>
			<RealValue>0.0</RealValue>
			<RealValue>0.0</RealValue>
		      </SUB>
		      <SUB>
			<RealValue>0.0</RealValue>
			<RealValue>0.0</RealValue>
		      </SUB>
		    </MUL>
		  </ADD>
		</SQRT>
		<RealValue>1.0</RealValue>
	      </LT>
	      <LT>
		<ABS>
		  <SUB>
		    <RealValue>0.0</RealValue>
		    <RealValue>0.0</RealValue>
		  </SUB>
		</ABS>
		<RealValue>1.0</RealValue>
	      </LT>
	    </AND>
	  </PreCondition>
	  <NodeBody>
	    <Assignment>
	      <IntegerVariable>foo</IntegerVariable>
	      <NumericRHS>
		<IntegerValue>3</IntegerValue>
	      </NumericRHS>
	    </Assignment>
	  </NodeBody>
	</Node>
	<Node NodeType="Assignment">
	  <NodeId>SimpleAssignment2</NodeId>
	  <VariableDeclarations>
            <DeclareVariable>
              <Name>x</Name>
              <Type>Real</Type>
              <InitialValue>
                <RealValue>0.0</RealValue>
              </InitialValue>
            </DeclareVariable>
            <DeclareVariable>
              <Name>y</Name>
              <Type>Real</Type>
              <InitialValue>
                <RealValue>0.0</RealValue>
              </InitialValue>
            </DeclareVariable>
            <DeclareVariable>
              <Name>bar</Name>
              <Type>Integer</Type>
              <InitialValue>
                <IntegerValue>0</IntegerValue>
              </InitialValue>
            </DeclareVariable>
	  </VariableDeclarations>
	  <PreCondition>
	    <AND>
	      <LT>
		<SQRT>
		  <ADD>
		    <MUL>
		      <SUB>
			<RealVariable>x</RealVariable>
			<RealVariable>y</RealVariable>
		      </SUB>
		      <SUB>
			<RealVariable>x</RealVariable>
			<RealVariable>y</RealVariable>
		      </SUB>
		    </MUL>
		    <MUL>
		      <SUB>
			<RealVariable>y</RealVariable>
			<RealVariable>x</RealVariable>
		      </SUB>
		      <SUB>
			<RealVariable>y</RealVariable>
			<RealVariable>x</RealVariable>
		      </SUB>
		    </MUL>
		  </ADD>
		</SQRT>
		<RealValue>1.0</RealValue>
	      </LT>
	      <LT>
		<ABS>
		  <SUB>
		    <RealVariable>x</RealVariable>
		    <RealVariable>y</RealVariable>
		  </SUB>
		</ABS>
		<RealValue>1.0</RealValue>
	      </LT>
	    </AND>
	  </PreCondition>
	  <NodeBody>
	    <Assignment>
	      <IntegerVariable>bar</IntegerVariable>
	      <NumericRHS>
		<IntegerValue>3</IntegerValue>
	      </NumericRHS>
	    </Assignment>
	  </NodeBody>
	</Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
