<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.3 on Mon Jun  4 14:45:35 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="name" type="string">
      <Value>Three</Value>
    </State>
    <State name="name2" type="string">
      <Value>Five</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
