<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Fri Feb  8 18:38:59 2008 -->
<PLEXILScript>
  <Script>
    <CommandAck name="foot-in-mouth" type="bool" >
      <Result>1</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
