module MAVLink
{
    struct GPSInfo
    {
        unsigned long id;
        double time;
        double latitude;
        double longitude;
        double absoluteAltitude;
        double relativeAltitude;
        double xVelocity;
        double yVelocity;
        double zVelocity;
    };
    #pragma keylist GPSInfo
};

