#!/bin/sh

if [ ! $PLEXIL_HOME ]
  then
    echo Error: Please set environment variable PLEXIL_HOME
    echo to the full pathname of your root 'plexil' directory.
    exit 1
fi

. $PLEXIL_HOME/scripts/plexil-setup.sh
prog=$PLEXIL_HOME/src/exec/test/exec-module-tests

if [ ! -e $prog ]
  then
    echo Exec module test executable not found.  Type 'make' to build it.
    exit 1
fi

$prog

