<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Feb  7 19:40:38 2008 -->
<PLEXILScript>
  <InitialState>
    <State name="CommandName" type="string" >
      <Value>get-string</Value>
    </State>
  </InitialState>
  <Script>
    <Command name="get-string" type="string" >
      <Result>fred</Result>
    </Command>
    <CommandAck name="get-string" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
