<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Aug 30 14:30:12 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="barfoo" type="string" >
      <Value>the-command</Value>
    </State>
  </InitialState>
  <Script>
    <CommandAck name="the-command" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
