<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Mon Jul 30 16:49:31 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="time" type="real">
      <Value>0.0</Value>
    </State>
    <State name="foo" type="int">
      <Value>5</Value>
    </State>
  </InitialState>
  <Script>
    <State name="foo" type="int">
      <Value>7</Value>
    </State>
    <State name="time" type="real">
      <Value>1.0</Value>
    </State>
    <State name="foo" type="int">
      <Value>6</Value>
    </State>
  </Script>
</PLEXILScript>
