<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Fri Feb  8 18:41:04 2008 -->
<PLEXILScript>
  <Script>
    <CommandAck name="store" type="bool" >
      <Result>1</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
