#! /bin/sh

# Generates a concise textual summary of a Core PLEXIL XML file.  

# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

usage="summarize-plexil input-file [ result-file ] [ transform-file ]"

# The result-file defaults to summary.txt.  The tranform-file defaults to
# summarize-plexil.xsl.

# Check environment variables

if [ -z "$PLEXIL_HOME" ]
  then
    echo Please set environment variable PLEXIL_HOME
    echo to the absolute pathname of your 'plexil' directory.
    exit 1
fi

# Defaults

transform_file="$PLEXIL_HOME/schema/summarize-plexil.xsl"
result_file="summary.txt"

# Location of the Saxon XSLT processor
saxon_jar="$PLEXIL_HOME/jars/saxon9he.jar"
 
# Determine argument values, overriding defaults when specified.

if [ $# = 3 ]
  then
    input_file=$1
    result_file=$2
    transform_file=$3
  elif [ $# = 2 ]
    then
      input_file=$1
      result_file=$2
  elif [ $# = 1 ]
    then
      input_file=$1
  else
    echo $usage
    exit 1
fi

JAVA=java
if [ -n "$JAVA_HOME" ]
then
    JAVA=$JAVA_HOME/bin/java
fi

echo "Summarizing $input_file ..."
$JAVA -jar $saxon_jar -o $result_file $input_file $transform_file 
echo Summary written to $result_file
