<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator">
  <Node NodeType="NodeList" FileName="SimpleDrive.ple" LineNo="26" ColNo="14">
    <NodeId>SimpleDrive</NodeId>
    <EndCondition>
      <EQInternal>
        <NodeStateVariable>
          <NodeId>TakeSample</NodeId>
        </NodeStateVariable>
        <NodeStateValue>FINISHED</NodeStateValue>
      </EQInternal>
    </EndCondition>
    <PostCondition>
      <EQInternal>
        <NodeOutcomeVariable>
          <NodeId>TakeSample</NodeId>
        </NodeOutcomeVariable>
        <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
      </EQInternal>
    </PostCondition>
    <NodeBody>
      <NodeList>
        <Node NodeType="Command" FileName="SimpleDrive.ple" LineNo="30" ColNo="10">
          <NodeId>Drive</NodeId>
          <PreCondition>
            <NOT>
              <LookupNow>
                <Name>
                  <StringValue>At</StringValue>
                </Name>
                <Arguments>
                  <StringValue>Rock</StringValue>
                </Arguments>
              </LookupNow>
            </NOT>
          </PreCondition>
          <RepeatCondition>
            <NOT>
              <LookupOnChange>
                <Name>
                  <StringValue>At</StringValue>
                </Name>
                <Arguments>
                  <StringValue>Rock</StringValue>
                </Arguments>
              </LookupOnChange>
            </NOT>
          </RepeatCondition>
          <EndCondition>
            <LookupOnChange>
              <Name>
                <StringValue>At</StringValue>
              </Name>
              <Arguments>
                <StringValue>Rock</StringValue>
              </Arguments>
            </LookupOnChange>
          </EndCondition>
          <NodeBody>
            <Command>
              <Name>
                <StringValue>drive</StringValue>
              </Name>
              <Arguments>
                <RealValue>1.0</RealValue>
              </Arguments>
            </Command>
          </NodeBody>
        </Node>
        <Node NodeType="Command" FileName="SimpleDrive.ple" LineNo="36" ColNo="15">
          <NodeId>TakeSample</NodeId>
          <StartCondition>
            <EQInternal>
              <NodeStateVariable>
                <NodeId>Drive</NodeId>
              </NodeStateVariable>
              <NodeStateValue>FINISHED</NodeStateValue>
            </EQInternal>
          </StartCondition>
          <InvariantCondition>
            <LookupOnChange>
              <Name>
                <StringValue>At</StringValue>
              </Name>
              <Arguments>
                <StringValue>Rock</StringValue>
              </Arguments>
            </LookupOnChange>
          </InvariantCondition>
          <NodeBody>
            <Command>
              <Name>
                <StringValue>takeSample</StringValue>
              </Name>
            </Command>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
