<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator">
  <Node NodeType="NodeList" FileName="SafeDrive.ple" LineNo="28" ColNo="1">
    <NodeId>SafeDrive</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>pictures</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
    <EndCondition>
      <OR>
        <LookupOnChange>
          <Name>
            <StringValue>Rover.WheelStuck</StringValue>
          </Name>
        </LookupOnChange>
        <EQNumeric>
          <IntegerVariable>pictures</IntegerVariable>
          <IntegerValue>10</IntegerValue>
        </EQNumeric>
      </OR>
    </EndCondition>
    <NodeBody>
      <NodeList>
        <Node NodeType="NodeList" FileName="SafeDrive.ple" LineNo="33" ColNo="5">
          <NodeId>Loop</NodeId>
          <RepeatCondition>
            <NOT>
              <LookupOnChange>
                <Name>
                  <StringValue>Rover.WheelStuck</StringValue>
                </Name>
              </LookupOnChange>
            </NOT>
          </RepeatCondition>
          <NodeBody>
            <NodeList>
              <Node NodeType="Command" FileName="SafeDrive.ple" LineNo="38" ColNo="9">
                <NodeId>OneMeter</NodeId>
                <NodeBody>
                  <Command>
                    <Name>
                      <StringValue>Rover.Drive</StringValue>
                    </Name>
                    <Arguments>
                      <IntegerValue>1</IntegerValue>
                    </Arguments>
                  </Command>
                </NodeBody>
              </Node>
              <Node NodeType="Command" FileName="SafeDrive.ple" LineNo="43" ColNo="9">
                <NodeId>TakePic</NodeId>
                <StartCondition>
                  <AND>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>OneMeter</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                    <LT>
                      <IntegerVariable>pictures</IntegerVariable>
                      <IntegerValue>10</IntegerValue>
                    </LT>
                  </AND>
                </StartCondition>
                <NodeBody>
                  <Command>
                    <Name>
                      <StringValue>Rover.TakePicture</StringValue>
                    </Name>
                  </Command>
                </NodeBody>
              </Node>
              <Node NodeType="Assignment" FileName="SafeDrive.ple" LineNo="49" ColNo="9">
                <NodeId>Counter</NodeId>
                <StartCondition>
                  <EQInternal>
                    <NodeStateVariable>
                      <NodeId>TakePic</NodeId>
                    </NodeStateVariable>
                    <NodeStateValue>FINISHED</NodeStateValue>
                  </EQInternal>
                </StartCondition>
                <PreCondition>
                  <LT>
                    <IntegerVariable>pictures</IntegerVariable>
                    <IntegerValue>10</IntegerValue>
                  </LT>
                </PreCondition>
                <NodeBody>
                  <Assignment>
                    <IntegerVariable>pictures</IntegerVariable>
                    <NumericRHS>
                      <ADD>
                        <IntegerVariable>pictures</IntegerVariable>
                        <IntegerValue>1</IntegerValue>
                      </ADD>
                    </NumericRHS>
                  </Assignment>
                </NodeBody>
              </Node>
            </NodeList>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
