//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GPSInfo.cpp
//  Source: /home/mfeliu/Desktop/icarous/icarous-legacy/C++/include/DDS/topics/GPSInfo.idl
//  Generated: Mon Dec 18 16:50:36 2017
//  OpenSplice 6.7.170912OSS
//  
//******************************************************************

#include "GPSInfo.h"




