<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Tue Aug 28 17:21:48 2007 -->
<PLEXILScript>
  <Script>
    <Command name="get-a2" type="string-array" >
      <Result>hello</Result>
      <Result>world</Result>
    </Command>
    <CommandAck name="get-a2" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
    <Command name="get-a3" type="bool-array" >
      <Result>0</Result>
      <Result>0</Result>
      <Result>0</Result>
      <Result>1</Result>
    </Command>
    <CommandAck name="get-a3" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
