<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Mon Jul 30 15:24:19 2007 -->
<PLEXILScript>
  <Script>
    <CommandAck name="foo" type="string">
      <Param type="string">TestArg</Param>
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
