<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0b on Thu Jan 25 19:43:44 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="A" type="int">
      <Param>is</Param>
      <Value>1</Value>
    </State>
    <State name="B" type="int">
      <Param>is</Param>
      <Value>2</Value>
    </State>
    <State name="C" type="int">
      <Param>is</Param>
      <Value>3</Value>
    </State>
  </InitialState>
  <Script>
    <CommandAck name="Execute1" type="string">
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
