<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Wed Jan 23 20:46:41 2008 -->
<PLEXILScript>
  <InitialState>
    <State name="foo" type="string" >
      <Param type="string" >p1</Param>
      <Value>mary</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
