<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Wed Jul 23 17:37:40 2008 -->
<PLEXILScript>
  <InitialState>
    <State name="foo" type="int" >
      <Value>5</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
