<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp -->
<PLEXILScript>
  <InitialState>
    <State name="Goal" type="bool" >
      <Value>false</Value>
    </State>
  </InitialState>
  <Script>
    <CommandAck name="getGoal" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
    <State name="Goal" type="bool" >
      <Value>false</Value>
    </State>
    <CommandAck name="getGoal" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
    <State name="Goal" type="bool" >
      <Value>false</Value>
    </State>
    <State name="Goal" type="bool" >
      <Value>true</Value>
    </State>
    <CommandAck name="getGoal" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
    <State name="Goal" type="bool" >
      <Value>true</Value>
    </State>
  </Script>
</PLEXILScript>
