<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator">
  <Node NodeType="NodeList" epx="Concurrence">
    <NodeId>InterfaceTest</NodeId>
    <Interface>
      <In>
        <DeclareVariable>
          <Name>Sin</Name>
          <Type>String</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Rin</Name>
          <Type>Real</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Iin</Name>
          <Type>Integer</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Din</Name>
          <Type>Real</Type>
        </DeclareVariable>
      </In>
      <InOut>
        <DeclareVariable>
          <Name>Sinout</Name>
          <Type>String</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Rinout</Name>
          <Type>Real</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Iinout</Name>
          <Type>Integer</Type>
        </DeclareVariable>
        <DeclareVariable>
          <Name>Dinout</Name>
          <Type>Real</Type>
        </DeclareVariable>
      </InOut>
    </Interface>
    <NodeBody>
      <NodeList>
        <Node NodeType="Assignment">
          <NodeId>A</NodeId>
          <NodeBody>
            <Assignment>
              <StringVariable>Sinout</StringVariable>
              <StringRHS>
                <StringValue>Sin</StringValue>
              </StringRHS>
            </Assignment>
          </NodeBody>
        </Node>
        <Node NodeType="Assignment">
          <NodeId>B</NodeId>
          <NodeBody>
            <Assignment>
              <StringVariable>Rinout</StringVariable>
              <StringRHS>
                <StringValue>Rin</StringValue>
              </StringRHS>
            </Assignment>
          </NodeBody>
        </Node>
        <Node NodeType="Assignment">
          <NodeId>C</NodeId>
          <NodeBody>
            <Assignment>
              <RealVariable>Dinout</RealVariable>
              <NumericRHS>
                <RealValue>1.5</RealValue>
              </NumericRHS>
            </Assignment>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
