The Launcher adapter allows a plan to spawn other plans for execution,
and monitor their execution status.

Launcher provides the following commands:

- String Command StartPlan(String planName [, String paramName, Any paramValue]* );

 Constructs a LibraryCall node which calls the named plan with the
 given parameter name-value pairs, and queues it for execution. Plan
 files are loaded as library nodes, that is, from the library path
 specified at executive launch time.

 Returns the generated name of the constructed LibraryCall node, for
 use with the ExitPlan command and the status query lookups below.

- Command ExitPlan(String planName);

 Causes the named top-level plan to exit by changing the value of the
 ExitPlan(planName) lookup to true. This triggers the ExitCondition of
 the generated wrapper node.

 This can be used with plans not generated by the Launcher adapter as
 well, but requires those plans to reference the ExitPlan(planName)
 lookup.

- Boolean Lookup ExitPlan(String planName);

 Used by the ExitPlan command (see above). The value is UNKNOWN until
 the ExitPlan command is executed with the same plan name. After the
 command, the lookup's value is true.

- String Lookup PlanState(String planName);

 Returns a string naming the current state of the named top-level
 node. When the node finishes, its final state (which should be
 "FINISHED") is cached.

- String Lookup PlanOutcome(String planName);

 Returns a string naming the outcome of the named top-level node, or
 the distinguished value UNKNOWN if the node has not transitioned to
 ITERATION_ENDED yet. When the node finishes, its final outcome value
 is cached.

- String Lookup PlanFailureType(String planName);

 Returns a string naming the failure type of the named top-level node,
 or the distinguished value UNKNOWN if the node has no failure type,
 i.e. it has not yet finished or finished with an outcome of SUCCESS.
