<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Jan 24 15:44:14 2008 -->
<PLEXILScript>
  <Script>
    <Command name="get-string" type="string" >
      <Result>fred</Result>
    </Command>
    <CommandAck name="get-string" type="string" >
      <Result>COMMAND_SUCCESS</Result>
    </CommandAck>
  </Script>
</PLEXILScript>
