/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "TrafficMonitor_proxy.h"

void _wrap_TrafficMonitor_DAA_set(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_TrafficMonitor_DAA_get(SwigObj * carg1);
void _wrap_TrafficMonitor_KMB_set(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_TrafficMonitor_KMB_get(SwigObj * carg1);
TrafficMonitor * _wrap_new_TrafficMonitor(SwigObj * carg1);
bool _wrap_TrafficMonitor_CheckTurnConflict(SwigObj * carg1, double carg2, double carg3, double carg4, double carg5);
bool _wrap_TrafficMonitor_MonitorTraffic(SwigObj * carg1, bool carg2, double carg3, /*aaa*/ double * carg4, /*aaa*/ double * carg5, /*aaa*/ double * carg6);
void _wrap_TrafficMonitor_GetVisualizationBands(SwigObj * carg1, SwigObj * carg2);
void _wrap_delete_TrafficMonitor(TrafficMonitor * carg1);

void TrafficMonitor_DAA_set(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_TrafficMonitor_DAA_set(carg1, carg2);
}
SwigObj * TrafficMonitor_DAA_get(SwigObj * carg1) {
  return _wrap_TrafficMonitor_DAA_get(carg1);
}
void TrafficMonitor_KMB_set(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_TrafficMonitor_KMB_set(carg1, carg2);
}
SwigObj * TrafficMonitor_KMB_get(SwigObj * carg1) {
  return _wrap_TrafficMonitor_KMB_get(carg1);
}
TrafficMonitor * new_TrafficMonitor(SwigObj * carg1) {
  return _wrap_new_TrafficMonitor(carg1);
}
bool TrafficMonitor_CheckTurnConflict(SwigObj * carg1, double carg2, double carg3, double carg4, double carg5) {
  return _wrap_TrafficMonitor_CheckTurnConflict(carg1, carg2, carg3, carg4, carg5);
}
bool TrafficMonitor_MonitorTraffic(SwigObj * carg1, bool carg2, double carg3, /*aaa*/ double * carg4, /*aaa*/ double * carg5, /*aaa*/ double * carg6) {
  return _wrap_TrafficMonitor_MonitorTraffic(carg1, carg2, carg3, carg4, carg5, carg6);
}
void TrafficMonitor_GetVisualizationBands(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_TrafficMonitor_GetVisualizationBands(carg1, carg2);
}
void delete_TrafficMonitor(TrafficMonitor * carg1) {
  return _wrap_delete_TrafficMonitor(carg1);
}

