#! /usr/bin/env bash

# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

osname=`uname`
if [ "Darwin" = "$osname" ]
then
    # FIXME: sensitive to changes in output format
    netstat -anfinet | grep '^\(tc\|ud\)p' \
        | sed -E -e 's/^(tc|ud)p[46]+ +[0-9]+ + [0-9]+ +[0-9\.\*]+\.([0-9]+) +[0-9*].*$/\2/g' \
        | grep -v '\*\.\*'
    netstat -anfinet6 | grep '^\(tc\|ud\)p' \
        | sed -E -e 's/^(tc|ud)p[46]+ +[0-9]+ + [0-9]+ +[0-9A-Fa-flo%\:\*]+\.([0-9]+) +[0-9A-Fa-f\:\*].*$/\2/g' \
        | grep -v '\*\.\*'
elif [ "Linux" = "$osname" ]
then
    netstat -anAinet | grep '^\(tc\|ud\)p' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
    netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
elif [ "FreeBSD" = "$osname" ]
then
    netstat -anfinet | grep '^\(tc\|ud\)p4' \
        | sed -E -e 's/^...4 +[0-9]+ +[0-9]+ (\*|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+) .*$/\2/g' \
	| grep -v '\*\.\*'
    netstat -anfinet6 | grep '^\(tc\|ud\)p6' \
        | sed -E -e 's/^...6 +[0-9]+ +[0-9]+ [0-9a-floA-F:%\*]+\.([0-9]+).*$/\1/g' \
	| grep -v '\*\.\*'
else
    echo "Error: Don't know how to get active port list on $osname"
    exit 1
fi
