//
// Created by research133 on 11/20/17.
//

#ifndef CFETOP_SCH_TBLIDS_H_H
#define CFETOP_SCH_TBLIDS_H_H

#define INTERFACE_GS_WAKEUP_MIDX 30
#define INTERFACE_AP_WAKEUP_MIDX 31

#endif //CFETOP_SCH_TBLIDS_H_H
