//
// Created by research133 on 11/20/17.
//

#ifndef CFETOP_SCH_TBLIDS_H_H
#define CFETOP_SCH_TBLIDS_H_H

#define INTERFACE_GS_WAKEUP_MIDX 30
#define INTERFACE_AP_WAKEUP_MIDX 31
#define PLEXIL_WAKEUP_MIDX 32
#define GEOFENCE_WAKEUP_MIDX 33
#define TRAFFIC_WAKEUP_MIDX 34
#define TRAJECTORY_WAKEUP_MIDX 35
#define TRACKING_WAKEUP_MIDX 36

#endif //CFETOP_SCH_TBLIDS_H_H
