/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GEOFENCE_INFO PACKING
package com.MAVLink.icarous;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Geo fence information
*/
public class msg_geofence_info extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_GEOFENCE_INFO = 222;
    public static final int MAVLINK_MSG_LENGTH = 15;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GEOFENCE_INFO;


      
    /**
    *  Fence floor height 
    */
    public float fenceFloor;
      
    /**
    *  Fence ceiling height 
    */
    public float fenceCeiling;
      
    /**
    *  Number of polygon verticies 
    */
    public float numVertices;
      
    /**
    * Flag, 0-new fence, 1-remove existing fence
    */
    public short msgType;
      
    /**
    * Flag, 0-keep in, 1-keep out
    */
    public short fenceType;
      
    /**
    *  Geo-fence ID
    */
    public short fenceID;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_GEOFENCE_INFO;
              
        packet.payload.putFloat(fenceFloor);
              
        packet.payload.putFloat(fenceCeiling);
              
        packet.payload.putFloat(numVertices);
              
        packet.payload.putUnsignedByte(msgType);
              
        packet.payload.putUnsignedByte(fenceType);
              
        packet.payload.putUnsignedByte(fenceID);
        
        return packet;
    }

    /**
    * Decode a geofence_info message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.fenceFloor = payload.getFloat();
              
        this.fenceCeiling = payload.getFloat();
              
        this.numVertices = payload.getFloat();
              
        this.msgType = payload.getUnsignedByte();
              
        this.fenceType = payload.getUnsignedByte();
              
        this.fenceID = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_geofence_info(){
        msgid = MAVLINK_MSG_ID_GEOFENCE_INFO;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_geofence_info(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_GEOFENCE_INFO;
        unpack(mavLinkPacket.payload);        
    }

                
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_GEOFENCE_INFO -"+" fenceFloor:"+fenceFloor+" fenceCeiling:"+fenceCeiling+" numVertices:"+numVertices+" msgType:"+msgType+" fenceType:"+fenceType+" fenceID:"+fenceID+"";
    }
}
        