/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMMAND_ACKNOWLEDGEMENT PACKING
package com.MAVLink.icarous;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Acknowledgement
*/
public class msg_command_acknowledgement extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT = 224;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT;


      
    /**
    * Acknowledgement type (0-waypoints,1-geofence)
    */
    public short acktype;
      
    /**
    * 1-success,0-failure
    */
    public short value;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT;
              
        packet.payload.putUnsignedByte(acktype);
              
        packet.payload.putUnsignedByte(value);
        
        return packet;
    }

    /**
    * Decode a command_acknowledgement message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.acktype = payload.getUnsignedByte();
              
        this.value = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_command_acknowledgement(){
        msgid = MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_command_acknowledgement(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_COMMAND_ACKNOWLEDGEMENT -"+" acktype:"+acktype+" value:"+value+"";
    }
}
        