/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "TrafficMonitor_proxy.h"

void _wrap_TrafficMonitor_DAA_set(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_TrafficMonitor_DAA_get(SwigObj * carg1);
void _wrap_TrafficMonitor_KMB_set(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_TrafficMonitor_KMB_get(SwigObj * carg1);
TrafficMonitor * _wrap_new_TrafficMonitor(bool carg1, /*aaa*/ char * carg2);
int _wrap_TrafficMonitor_InputTraffic(SwigObj * carg1, int carg2, /*aaa*/ double * carg3, /*aaa*/ double * carg4);
void _wrap_TrafficMonitor_MonitorTraffic(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, double carg4);
bool _wrap_TrafficMonitor_MonitorWPFeasibility(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, /*aaa*/ double * carg4);
bool _wrap_TrafficMonitor_CheckSafeToTurn(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, double carg4, double carg5);
bool _wrap_TrafficMonitor_CheckTurnConflict(SwigObj * carg1, double carg2, double carg3, double carg4, double carg5);
void _wrap_TrafficMonitor_GetTrackBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14);
void _wrap_TrafficMonitor_GetGSBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14);
void _wrap_TrafficMonitor_GetVSBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14);
void _wrap_TrafficMonitor_GetAltBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14);
void _wrap_delete_TrafficMonitor(TrafficMonitor * carg1);

void TrafficMonitor_DAA_set(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_TrafficMonitor_DAA_set(carg1, carg2);
}
SwigObj * TrafficMonitor_DAA_get(SwigObj * carg1) {
  return _wrap_TrafficMonitor_DAA_get(carg1);
}
void TrafficMonitor_KMB_set(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_TrafficMonitor_KMB_set(carg1, carg2);
}
SwigObj * TrafficMonitor_KMB_get(SwigObj * carg1) {
  return _wrap_TrafficMonitor_KMB_get(carg1);
}
TrafficMonitor * new_TrafficMonitor(bool carg1, /*aaa*/ char * carg2) {
  return _wrap_new_TrafficMonitor(carg1, carg2);
}
int TrafficMonitor_InputTraffic(SwigObj * carg1, int carg2, /*aaa*/ double * carg3, /*aaa*/ double * carg4) {
  return _wrap_TrafficMonitor_InputTraffic(carg1, carg2, carg3, carg4);
}
void TrafficMonitor_MonitorTraffic(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, double carg4) {
  return _wrap_TrafficMonitor_MonitorTraffic(carg1, carg2, carg3, carg4);
}
bool TrafficMonitor_MonitorWPFeasibility(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, /*aaa*/ double * carg4) {
  return _wrap_TrafficMonitor_MonitorWPFeasibility(carg1, carg2, carg3, carg4);
}
bool TrafficMonitor_CheckSafeToTurn(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3, double carg4, double carg5) {
  return _wrap_TrafficMonitor_CheckSafeToTurn(carg1, carg2, carg3, carg4, carg5);
}
bool TrafficMonitor_CheckTurnConflict(SwigObj * carg1, double carg2, double carg3, double carg4, double carg5) {
  return _wrap_TrafficMonitor_CheckTurnConflict(carg1, carg2, carg3, carg4, carg5);
}
void TrafficMonitor_GetTrackBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14) {
  return _wrap_TrafficMonitor_GetTrackBands(carg1, carg2, carg3, carg4, carg5, carg6, carg7, carg8, carg9, carg10, carg11, carg12, carg13, carg14);
}
void TrafficMonitor_GetGSBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14) {
  return _wrap_TrafficMonitor_GetGSBands(carg1, carg2, carg3, carg4, carg5, carg6, carg7, carg8, carg9, carg10, carg11, carg12, carg13, carg14);
}
void TrafficMonitor_GetVSBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14) {
  return _wrap_TrafficMonitor_GetVSBands(carg1, carg2, carg3, carg4, carg5, carg6, carg7, carg8, carg9, carg10, carg11, carg12, carg13, carg14);
}
void TrafficMonitor_GetAltBands(SwigObj * carg1, int * carg2, int * carg3, double * carg4, double * carg5, int * carg6, int * carg7, double * carg8, double * carg9, double * carg10, double * carg11, double * carg12, double * carg13, double * carg14) {
  return _wrap_TrafficMonitor_GetAltBands(carg1, carg2, carg3, carg4, carg5, carg6, carg7, carg8, carg9, carg10, carg11, carg12, carg13, carg14);
}
void delete_TrafficMonitor(TrafficMonitor * carg1) {
  return _wrap_delete_TrafficMonitor(carg1);
}

