//
// Created by Swee Balachadran on 11/20/17.
//

#ifndef CFETOP_SCH_TBLIDS_H_H
#define CFETOP_SCH_TBLIDS_H_H

#define FREQ_50_WAKEUP_MIDX 30
#define FREQ_30_WAKEUP_MIDX 31
#define FREQ_20_WAKEUP_MIDX 32
#define FREQ_10_WAKEUP_MIDX 33
#define FREQ_05_WAKEUP_MIDX 34
#define FREQ_01_WAKEUP_MIDX 35

#endif //CFETOP_SCH_TBLIDS_H_H
