<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>AtomicAssignment</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>x</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
      <DeclareVariable>
        <Name>y</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>1</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <NodeList>
        <Node NodeType="Assignment"><NodeId>xy</NodeId><NodeBody>
            <Assignment>
              <IntegerVariable>x</IntegerVariable>
              <NumericRHS>
                <IntegerVariable>y</IntegerVariable>
              </NumericRHS>
            </Assignment>
          </NodeBody></Node>
        <Node NodeType="Assignment"><NodeId>yx</NodeId><NodeBody>
            <Assignment>
              <IntegerVariable>y</IntegerVariable>
              <NumericRHS>
                <IntegerVariable>x</IntegerVariable>
              </NumericRHS>
            </Assignment>
          </NodeBody></Node>
        <Node NodeType="Command"><NodeId>check</NodeId><StartCondition><AND><EQInternal><NodeStateVariable><NodeId>xy</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal><EQInternal><NodeStateVariable><NodeId>yx</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></AND></StartCondition><NodeBody>
            <Command>
              <Name>
<StringValue>check</StringValue>
              </Name>
              <Arguments>
                <IntegerVariable>x</IntegerVariable>
                <IntegerVariable>y</IntegerVariable>
              </Arguments>
            </Command>
          </NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>