/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ICAROUS_GEOFENCE PACKING
package com.MAVLink.icarous;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Geo fence information
*/
public class msg_icarous_geofence extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_ICAROUS_GEOFENCE = 151;
    public static final int MAVLINK_MSG_LENGTH = 87;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ICAROUS_GEOFENCE;


      
    /**
    *  Fence floor height 
    */
    public float fenceFloor;
      
    /**
    *  Fence ceiling height 
    */
    public float fenceCeiling;
      
    /**
    *  Number of polygon verticies 
    */
    public float numVertices;
      
    /**
    * Vertex1
    */
    public float vertex1[] = new float[3];
      
    /**
    * Vertex2
    */
    public float vertex2[] = new float[3];
      
    /**
    * Vertex3
    */
    public float vertex3[] = new float[3];
      
    /**
    * Vertex4
    */
    public float vertex4[] = new float[3];
      
    /**
    * Vertex5
    */
    public float vertex5[] = new float[3];
      
    /**
    * Vertex6
    */
    public float vertex6[] = new float[3];
      
    /**
    * Flag, 0-new fence, 1-append coordinates to existing fence, 2-remove existing fence
    */
    public short msgType;
      
    /**
    * Flag, 0-keep in, 1-keep out
    */
    public short fenceType;
      
    /**
    *  Geo-fence ID
    */
    public short fenceID;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_ICAROUS_GEOFENCE;
              
        packet.payload.putFloat(fenceFloor);
              
        packet.payload.putFloat(fenceCeiling);
              
        packet.payload.putFloat(numVertices);
              
        
        for (int i = 0; i < vertex1.length; i++) {
            packet.payload.putFloat(vertex1[i]);
        }
                    
              
        
        for (int i = 0; i < vertex2.length; i++) {
            packet.payload.putFloat(vertex2[i]);
        }
                    
              
        
        for (int i = 0; i < vertex3.length; i++) {
            packet.payload.putFloat(vertex3[i]);
        }
                    
              
        
        for (int i = 0; i < vertex4.length; i++) {
            packet.payload.putFloat(vertex4[i]);
        }
                    
              
        
        for (int i = 0; i < vertex5.length; i++) {
            packet.payload.putFloat(vertex5[i]);
        }
                    
              
        
        for (int i = 0; i < vertex6.length; i++) {
            packet.payload.putFloat(vertex6[i]);
        }
                    
              
        packet.payload.putUnsignedByte(msgType);
              
        packet.payload.putUnsignedByte(fenceType);
              
        packet.payload.putUnsignedByte(fenceID);
        
        return packet;
    }

    /**
    * Decode a icarous_geofence message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.fenceFloor = payload.getFloat();
              
        this.fenceCeiling = payload.getFloat();
              
        this.numVertices = payload.getFloat();
              
         
        for (int i = 0; i < this.vertex1.length; i++) {
            this.vertex1[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.vertex2.length; i++) {
            this.vertex2[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.vertex3.length; i++) {
            this.vertex3[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.vertex4.length; i++) {
            this.vertex4[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.vertex5.length; i++) {
            this.vertex5[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.vertex6.length; i++) {
            this.vertex6[i] = payload.getFloat();
        }
                
              
        this.msgType = payload.getUnsignedByte();
              
        this.fenceType = payload.getUnsignedByte();
              
        this.fenceID = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_icarous_geofence(){
        msgid = MAVLINK_MSG_ID_ICAROUS_GEOFENCE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_icarous_geofence(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_ICAROUS_GEOFENCE;
        unpack(mavLinkPacket.payload);        
    }

                            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_ICAROUS_GEOFENCE -"+" fenceFloor:"+fenceFloor+" fenceCeiling:"+fenceCeiling+" numVertices:"+numVertices+" vertex1:"+vertex1+" vertex2:"+vertex2+" vertex3:"+vertex3+" vertex4:"+vertex4+" vertex5:"+vertex5+" vertex6:"+vertex6+" msgType:"+msgType+" fenceType:"+fenceType+" fenceID:"+fenceID+"";
    }
}
        