/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ICAROUS_FLIGHTPLAN_UPDATE PACKING
package com.MAVLink.icarous;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Flight plan information 
*/
public class msg_icarous_flightplan_update extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE = 150;
    public static final int MAVLINK_MSG_LENGTH = 177;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE;


      
    /**
    * Standoff distance
    */
    public float standoffDist;
      
    /**
    * Maximum horizontal deviation from flight plan
    */
    public float maxHorDev;
      
    /**
    * Maximum vertical deviation from flight plan
    */
    public float maxVerDev;
      
    /**
    * Number of waypoints
    */
    public long numWaypoints;
      
    /**
    * Waypoint 1
    */
    public float wp1[] = new float[4];
      
    /**
    * Waypoint 2
    */
    public float wp2[] = new float[4];
      
    /**
    * Waypoint 3
    */
    public float wp3[] = new float[4];
      
    /**
    * Waypoint 4
    */
    public float wp4[] = new float[4];
      
    /**
    * Waypoint 5
    */
    public float wp5[] = new float[4];
      
    /**
    * Waypoint 6
    */
    public float wp6[] = new float[4];
      
    /**
    * Waypoint 7
    */
    public float wp7[] = new float[4];
      
    /**
    * Waypoint 8
    */
    public float wp8[] = new float[4];
      
    /**
    * Waypoint 9
    */
    public float wp9[] = new float[4];
      
    /**
    * Waypoint 10
    */
    public float wp10[] = new float[4];
      
    /**
    * Flag, 0-new flight plan,1-append waypoints to existingflight plan
    */
    public short msgType;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE;
              
        packet.payload.putFloat(standoffDist);
              
        packet.payload.putFloat(maxHorDev);
              
        packet.payload.putFloat(maxVerDev);
              
        packet.payload.putUnsignedInt(numWaypoints);
              
        
        for (int i = 0; i < wp1.length; i++) {
            packet.payload.putFloat(wp1[i]);
        }
                    
              
        
        for (int i = 0; i < wp2.length; i++) {
            packet.payload.putFloat(wp2[i]);
        }
                    
              
        
        for (int i = 0; i < wp3.length; i++) {
            packet.payload.putFloat(wp3[i]);
        }
                    
              
        
        for (int i = 0; i < wp4.length; i++) {
            packet.payload.putFloat(wp4[i]);
        }
                    
              
        
        for (int i = 0; i < wp5.length; i++) {
            packet.payload.putFloat(wp5[i]);
        }
                    
              
        
        for (int i = 0; i < wp6.length; i++) {
            packet.payload.putFloat(wp6[i]);
        }
                    
              
        
        for (int i = 0; i < wp7.length; i++) {
            packet.payload.putFloat(wp7[i]);
        }
                    
              
        
        for (int i = 0; i < wp8.length; i++) {
            packet.payload.putFloat(wp8[i]);
        }
                    
              
        
        for (int i = 0; i < wp9.length; i++) {
            packet.payload.putFloat(wp9[i]);
        }
                    
              
        
        for (int i = 0; i < wp10.length; i++) {
            packet.payload.putFloat(wp10[i]);
        }
                    
              
        packet.payload.putUnsignedByte(msgType);
        
        return packet;
    }

    /**
    * Decode a icarous_flightplan_update message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.standoffDist = payload.getFloat();
              
        this.maxHorDev = payload.getFloat();
              
        this.maxVerDev = payload.getFloat();
              
        this.numWaypoints = payload.getUnsignedInt();
              
         
        for (int i = 0; i < this.wp1.length; i++) {
            this.wp1[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp2.length; i++) {
            this.wp2[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp3.length; i++) {
            this.wp3[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp4.length; i++) {
            this.wp4[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp5.length; i++) {
            this.wp5[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp6.length; i++) {
            this.wp6[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp7.length; i++) {
            this.wp7[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp8.length; i++) {
            this.wp8[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp9.length; i++) {
            this.wp9[i] = payload.getFloat();
        }
                
              
         
        for (int i = 0; i < this.wp10.length; i++) {
            this.wp10[i] = payload.getFloat();
        }
                
              
        this.msgType = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_icarous_flightplan_update(){
        msgid = MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_icarous_flightplan_update(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE;
        unpack(mavLinkPacket.payload);        
    }

                                  
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_ICAROUS_FLIGHTPLAN_UPDATE -"+" standoffDist:"+standoffDist+" maxHorDev:"+maxHorDev+" maxVerDev:"+maxVerDev+" numWaypoints:"+numWaypoints+" wp1:"+wp1+" wp2:"+wp2+" wp3:"+wp3+" wp4:"+wp4+" wp5:"+wp5+" wp6:"+wp6+" wp7:"+wp7+" wp8:"+wp8+" wp9:"+wp9+" wp10:"+wp10+" msgType:"+msgType+"";
    }
}
        