/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "GeofenceMonitor_proxy.h"

void _wrap_GeofenceConflict_fenceId_set(SwigObj * carg1, int carg2);
int _wrap_GeofenceConflict_fenceId_get(SwigObj * carg1);
void _wrap_GeofenceConflict_violationStatus_set(SwigObj * carg1, bool carg2);
bool _wrap_GeofenceConflict_violationStatus_get(SwigObj * carg1);
void _wrap_GeofenceConflict_conflictstatus_set(SwigObj * carg1, bool carg2);
bool _wrap_GeofenceConflict_conflictstatus_get(SwigObj * carg1);
void _wrap_GeofenceConflict_recoveryPoint_set(SwigObj * carg1, /*aaa*/ double * carg2);
double * _wrap_GeofenceConflict_recoveryPoint_get(SwigObj * carg1);
void _wrap_GeofenceConflict__gf_set(SwigObj * carg1, SwigObj * carg2);
/*aaaaaa*/SwigObj * _wrap_GeofenceConflict__gf_get(SwigObj * carg1);
GeofenceConflict * _wrap_new_GeofenceConflict();
void _wrap_delete_GeofenceConflict(GeofenceConflict * carg1);
GeofenceMonitor * _wrap_new_GeofenceMonitor(/*aaa*/ double * carg1);
void _wrap_GeofenceMonitor_SetGeofenceParameters(SwigObj * carg1, /*aaa*/ double * carg2);
void _wrap_GeofenceMonitor_InputGeofenceData(SwigObj * carg1, int carg2, int carg3, int carg4, double carg5, double carg6, double *carg7[2]);
bool _wrap_GeofenceMonitor_CheckViolation(SwigObj * carg1, /*aaa*/ double * carg2, double carg3, double carg4, double carg5);
bool _wrap_GeofenceMonitor_CheckWPFeasibility(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3);
int _wrap_GeofenceMonitor_GetNumConflicts(SwigObj * carg1);
void _wrap_GeofenceMonitor_GetConflictStatus(SwigObj * carg1, bool * carg2);
void _wrap_GeofenceMonitor_GetConflict(SwigObj * carg1, int carg2, int * carg3, bool * carg4, bool * carg5, /*aaa*/ double * carg6, int * carg7);
void _wrap_GeofenceMonitor_GetClosestRecoveryPoint(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3);
void _wrap_GeofenceMonitor_ClearFences(SwigObj * carg1);
void _wrap_delete_GeofenceMonitor(GeofenceMonitor * carg1);

void GeofenceConflict_fenceId_set(SwigObj * carg1, int carg2) {
  return _wrap_GeofenceConflict_fenceId_set(carg1, carg2);
}
int GeofenceConflict_fenceId_get(SwigObj * carg1) {
  return _wrap_GeofenceConflict_fenceId_get(carg1);
}
void GeofenceConflict_violationStatus_set(SwigObj * carg1, bool carg2) {
  return _wrap_GeofenceConflict_violationStatus_set(carg1, carg2);
}
bool GeofenceConflict_violationStatus_get(SwigObj * carg1) {
  return _wrap_GeofenceConflict_violationStatus_get(carg1);
}
void GeofenceConflict_conflictstatus_set(SwigObj * carg1, bool carg2) {
  return _wrap_GeofenceConflict_conflictstatus_set(carg1, carg2);
}
bool GeofenceConflict_conflictstatus_get(SwigObj * carg1) {
  return _wrap_GeofenceConflict_conflictstatus_get(carg1);
}
void GeofenceConflict_recoveryPoint_set(SwigObj * carg1, /*aaa*/ double * carg2) {
  return _wrap_GeofenceConflict_recoveryPoint_set(carg1, carg2);
}
double * GeofenceConflict_recoveryPoint_get(SwigObj * carg1) {
  return _wrap_GeofenceConflict_recoveryPoint_get(carg1);
}
void GeofenceConflict__gf_set(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GeofenceConflict__gf_set(carg1, carg2);
}
/*aaaaaa*/SwigObj * GeofenceConflict__gf_get(SwigObj * carg1) {
  return _wrap_GeofenceConflict__gf_get(carg1);
}
GeofenceConflict * new_GeofenceConflict() {
  return _wrap_new_GeofenceConflict();
}
void delete_GeofenceConflict(GeofenceConflict * carg1) {
  return _wrap_delete_GeofenceConflict(carg1);
}
GeofenceMonitor * new_GeofenceMonitor(/*aaa*/ double * carg1) {
  return _wrap_new_GeofenceMonitor(carg1);
}
void GeofenceMonitor_SetGeofenceParameters(SwigObj * carg1, /*aaa*/ double * carg2) {
  return _wrap_GeofenceMonitor_SetGeofenceParameters(carg1, carg2);
}
void GeofenceMonitor_InputGeofenceData(SwigObj * carg1, int carg2, int carg3, int carg4, double carg5, double carg6, double *carg7[2]) {
  return _wrap_GeofenceMonitor_InputGeofenceData(carg1, carg2, carg3, carg4, carg5, carg6, carg7);
}
bool GeofenceMonitor_CheckViolation(SwigObj * carg1, /*aaa*/ double * carg2, double carg3, double carg4, double carg5) {
  return _wrap_GeofenceMonitor_CheckViolation(carg1, carg2, carg3, carg4, carg5);
}
bool GeofenceMonitor_CheckWPFeasibility(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3) {
  return _wrap_GeofenceMonitor_CheckWPFeasibility(carg1, carg2, carg3);
}
int GeofenceMonitor_GetNumConflicts(SwigObj * carg1) {
  return _wrap_GeofenceMonitor_GetNumConflicts(carg1);
}
void GeofenceMonitor_GetConflictStatus(SwigObj * carg1, bool * carg2) {
  return _wrap_GeofenceMonitor_GetConflictStatus(carg1, carg2);
}
void GeofenceMonitor_GetConflict(SwigObj * carg1, int carg2, int * carg3, bool * carg4, bool * carg5, /*aaa*/ double * carg6, int * carg7) {
  return _wrap_GeofenceMonitor_GetConflict(carg1, carg2, carg3, carg4, carg5, carg6, carg7);
}
void GeofenceMonitor_GetClosestRecoveryPoint(SwigObj * carg1, /*aaa*/ double * carg2, /*aaa*/ double * carg3) {
  return _wrap_GeofenceMonitor_GetClosestRecoveryPoint(carg1, carg2, carg3);
}
void GeofenceMonitor_ClearFences(SwigObj * carg1) {
  return _wrap_GeofenceMonitor_ClearFences(carg1);
}
void delete_GeofenceMonitor(GeofenceMonitor * carg1) {
  return _wrap_delete_GeofenceMonitor(carg1);
}

