<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="Empty">
      <NodeId>DoValue</NodeId>
      <Interface>
         <In>
            <DeclareVariable>
               <Name>foo</Name>
               <Type>Boolean</Type>
            </DeclareVariable>
         </In>
      </Interface>
      <StartCondition>
         <BooleanVariable>foo</BooleanVariable>
      </StartCondition>
   </Node>
</PlexilPlan>