<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator">
  <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="12" ColNo="2">
    <NodeId>DriveToSchool</NodeId>
    <InvariantCondition>
      <AND>
        <NOT>
          <OR>
            <EQInternal>
              <NodeOutcomeVariable>
                <NodeId>StartCar</NodeId>
              </NodeOutcomeVariable>
              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
              <NodeOutcomeVariable>
                <NodeId>HandleRain</NodeId>
              </NodeOutcomeVariable>
              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
              <NodeOutcomeVariable>
                <NodeId>SelectStation</NodeId>
              </NodeOutcomeVariable>
              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
              <NodeOutcomeVariable>
                <NodeId>DriveUntilAtSchool</NodeId>
              </NodeOutcomeVariable>
              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
            </EQInternal>
          </OR>
        </NOT>
      </AND>
    </InvariantCondition>
    <NodeBody>
      <NodeList>
        <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="23" ColNo="2">
          <NodeId>StartCar</NodeId>
          <PostCondition>
            <AND>
              <OR>
                <EQInternal>
                  <NodeOutcomeVariable>
                    <NodeId>KeyStart</NodeId>
                  </NodeOutcomeVariable>
                  <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
                </EQInternal>
                <EQInternal>
                  <NodeOutcomeVariable>
                    <NodeId>PushStart</NodeId>
                  </NodeOutcomeVariable>
                  <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
                </EQInternal>
              </OR>
            </AND>
          </PostCondition>
          <EndCondition>
            <OR>
              <EQInternal>
                <NodeOutcomeVariable>
                  <NodeId>KeyStart</NodeId>
                </NodeOutcomeVariable>
                <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
              </EQInternal>
              <EQInternal>
                <NodeOutcomeVariable>
                  <NodeId>PushStart</NodeId>
                </NodeOutcomeVariable>
                <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
              </EQInternal>
            </OR>
          </EndCondition>
          <NodeBody>
            <NodeList>
              <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="45" ColNo="2">
                <NodeId>KeyStart</NodeId>
                <PostCondition>
                  <LookupNow>
                    <Name>
                      <StringValue>car_started</StringValue>
                    </Name>
                  </LookupNow>
                </PostCondition>
                <NodeBody>
                  <NodeList>
                    <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="60" ColNo="2">
                      <NodeId>PrimeAccelerator</NodeId>
                      <Comment>Assume cold day with carbuerated engine!</Comment>
                      <VariableDeclarations>
                        <DeclareVariable>
                          <Name>count</Name>
                          <Type>Integer</Type>
                          <InitialValue>
                            <IntegerValue>0</IntegerValue>
                          </InitialValue>
                        </DeclareVariable>
                      </VariableDeclarations>
                      <EndCondition>
                        <OR>
                          <NOT>
                            <LT>
                              <IntegerVariable>count</IntegerVariable>
                              <IntegerValue>3</IntegerValue>
                            </LT>
                          </NOT>
                          <EQInternal>
                            <NodeStateVariable>
                              <NodeId>ep2cp_ForLoop</NodeId>
                            </NodeStateVariable>
                            <NodeStateValue>FINISHED</NodeStateValue>
                          </EQInternal>
                        </OR>
                      </EndCondition>
                      <NodeBody>
                        <NodeList>
                          <Node NodeType="NodeList">
                            <NodeId>ep2cp_ForLoop</NodeId>
                            <RepeatCondition>
                              <LT>
                                <IntegerVariable>count</IntegerVariable>
                                <IntegerValue>3</IntegerValue>
                              </LT>
                            </RepeatCondition>
                            <NodeBody>
                              <NodeList>
                                <Node NodeType="NodeList">
                                  <NodeId>ep2cp_ForDo</NodeId>
                                  <NodeBody>
                                    <NodeList>
                                      <Node NodeType="Command" FileName="DriveToSchool.ple" LineNo="80" ColNo="2">
                                        <NodeId>PressAccelerator</NodeId>
                                        <NodeBody>
                                          <Command>
                                            <Name>
                                              <StringValue>depress_accelerator</StringValue>
                                            </Name>
                                          </Command>
                                        </NodeBody>
                                      </Node>
                                    </NodeList>
                                  </NodeBody>
                                </Node>
                                <Node NodeType="Assignment">
                                  <NodeId>ep2cp_ForLoopUpdater</NodeId>
                                  <StartCondition>
                                    <EQInternal>
                                      <NodeStateVariable>
                                        <NodeId>ep2cp_ForDo</NodeId>
                                      </NodeStateVariable>
                                      <NodeStateValue>FINISHED</NodeStateValue>
                                    </EQInternal>
                                  </StartCondition>
                                  <NodeBody>
                                    <Assignment>
                                      <IntegerVariable>count</IntegerVariable>
                                      <NumericRHS>
                                        <ADD>
                                          <IntegerVariable>count</IntegerVariable>
                                          <IntegerValue>1</IntegerValue>
                                        </ADD>
                                      </NumericRHS>
                                    </Assignment>
                                  </NodeBody>
                                </Node>
                              </NodeList>
                            </NodeBody>
                          </Node>
                        </NodeList>
                      </NodeBody>
                    </Node>
                    <Node NodeType="Command">
                      <NodeId>DepressClutch</NodeId>
                      <StartCondition>
                        <AND>
                          <EQInternal>
                            <NodeStateVariable>
                              <NodeId>PrimeAccelerator</NodeId>
                            </NodeStateVariable>
                            <NodeStateValue>FINISHED</NodeStateValue>
                          </EQInternal>
                        </AND>
                      </StartCondition>
                      <NodeBody>
                        <Command>
                          <Name>
                            <StringValue>depress_clutch</StringValue>
                          </Name>
                        </Command>
                      </NodeBody>
                    </Node>
                    <Node NodeType="Command">
                      <NodeId>TurnKey</NodeId>
                      <StartCondition>
                        <AND>
                          <EQInternal>
                            <NodeStateVariable>
                              <NodeId>DepressClutch</NodeId>
                            </NodeStateVariable>
                            <NodeStateValue>FINISHED</NodeStateValue>
                          </EQInternal>
                        </AND>
                      </StartCondition>
                      <NodeBody>
                        <Command>
                          <Name>
                            <StringValue>turn_key</StringValue>
                          </Name>
                        </Command>
                      </NodeBody>
                    </Node>
                  </NodeList>
                </NodeBody>
              </Node>
              <Node NodeType="Command">
                <NodeId>PushStart</NodeId>
                <StartCondition>
                  <AND>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>KeyStart</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                  </AND>
                </StartCondition>
                <PostCondition>
                  <LookupNow>
                    <Name>
                      <StringValue>car_started</StringValue>
                    </Name>
                  </LookupNow>
                </PostCondition>
                <NodeBody>
                  <Command>
                    <Name>
                      <StringValue>push_start</StringValue>
                    </Name>
                  </Command>
                </NodeBody>
              </Node>
            </NodeList>
          </NodeBody>
        </Node>
        <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="100" ColNo="2">
          <NodeId>HandleRain</NodeId>
          <VariableDeclarations>
            <DeclareVariable>
              <Name>ep2cp_test</Name>
              <Type>Boolean</Type>
            </DeclareVariable>
          </VariableDeclarations>
          <StartCondition>
            <AND>
              <EQInternal>
                <NodeStateVariable>
                  <NodeId>StartCar</NodeId>
                </NodeStateVariable>
                <NodeStateValue>FINISHED</NodeStateValue>
              </EQInternal>
            </AND>
          </StartCondition>
          <NodeBody>
            <NodeList>
              <Node NodeType="Assignment">
                <NodeId>ep2cp_IfSetup</NodeId>
                <NodeBody>
                  <Assignment>
                    <BooleanVariable>ep2cp_test</BooleanVariable>
                    <BooleanRHS>
                      <LookupNow>
                        <Name>
                          <StringValue>raining</StringValue>
                        </Name>
                      </LookupNow>
                    </BooleanRHS>
                  </Assignment>
                </NodeBody>
              </Node>
              <Node NodeType="NodeList">
                <NodeId>ep2cp_IfBody</NodeId>
                <StartCondition>
                  <EQInternal>
                    <NodeStateVariable>
                      <NodeId>ep2cp_IfSetup</NodeId>
                    </NodeStateVariable>
                    <NodeStateValue>FINISHED</NodeStateValue>
                  </EQInternal>
                </StartCondition>
                <EndCondition>
                  <OR>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>ep2cp_IfTrueCase</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                    <NOT>
                      <BooleanVariable>ep2cp_test</BooleanVariable>
                    </NOT>
                  </OR>
                </EndCondition>
                <NodeBody>
                  <NodeList>
                    <Node NodeType="NodeList">
                      <NodeId>ep2cp_IfTrueCase</NodeId>
                      <StartCondition>
                        <BooleanVariable>ep2cp_test</BooleanVariable>
                      </StartCondition>
                      <NodeBody>
                        <NodeList>
                          <Node NodeType="Command">
                            <NodeId>Wipers</NodeId>
                            <NodeBody>
                              <Command>
                                <Name>
                                  <StringValue>turn_on_wipers</StringValue>
                                </Name>
                              </Command>
                            </NodeBody>
                          </Node>
                          <Node NodeType="Command">
                            <NodeId>Lights</NodeId>
                            <NodeBody>
                              <Command>
                                <Name>
                                  <StringValue>turn_on_lights</StringValue>
                                </Name>
                              </Command>
                            </NodeBody>
                          </Node>
                        </NodeList>
                      </NodeBody>
                    </Node>
                  </NodeList>
                </NodeBody>
              </Node>
            </NodeList>
          </NodeBody>
        </Node>
        <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="123" ColNo="2">
          <NodeId>SelectStation</NodeId>
          <VariableDeclarations>
            <DeclareVariable>
              <Name>ep2cp_test</Name>
              <Type>Boolean</Type>
            </DeclareVariable>
          </VariableDeclarations>
          <StartCondition>
            <AND>
              <EQInternal>
                <NodeStateVariable>
                  <NodeId>HandleRain</NodeId>
                </NodeStateVariable>
                <NodeStateValue>FINISHED</NodeStateValue>
              </EQInternal>
            </AND>
          </StartCondition>
          <NodeBody>
            <NodeList>
              <Node NodeType="Assignment">
                <NodeId>ep2cp_IfSetup</NodeId>
                <NodeBody>
                  <Assignment>
                    <BooleanVariable>ep2cp_test</BooleanVariable>
                    <BooleanRHS>
                      <LookupNow>
                        <Name>
                          <StringValue>no_passengers</StringValue>
                        </Name>
                      </LookupNow>
                    </BooleanRHS>
                  </Assignment>
                </NodeBody>
              </Node>
              <Node NodeType="NodeList">
                <NodeId>ep2cp_IfBody</NodeId>
                <StartCondition>
                  <EQInternal>
                    <NodeStateVariable>
                      <NodeId>ep2cp_IfSetup</NodeId>
                    </NodeStateVariable>
                    <NodeStateValue>FINISHED</NodeStateValue>
                  </EQInternal>
                </StartCondition>
                <EndCondition>
                  <OR>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>ep2cp_IfTrueCase</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>ep2cp_IfFalseCase</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                  </OR>
                </EndCondition>
                <NodeBody>
                  <NodeList>
                    <Node NodeType="NodeList">
                      <NodeId>ep2cp_IfTrueCase</NodeId>
                      <StartCondition>
                        <BooleanVariable>ep2cp_test</BooleanVariable>
                      </StartCondition>
                      <NodeBody>
                        <NodeList>
                          <Node NodeType="Command">
                            <NodeId>Radio</NodeId>
                            <NodeBody>
                              <Command>
                                <Name>
                                  <StringValue>select_radio</StringValue>
                                </Name>
                              </Command>
                            </NodeBody>
                          </Node>
                        </NodeList>
                      </NodeBody>
                    </Node>
                    <Node NodeType="NodeList">
                      <NodeId>ep2cp_IfFalseCase</NodeId>
                      <StartCondition>
                        <NOT>
                          <BooleanVariable>ep2cp_test</BooleanVariable>
                        </NOT>
                      </StartCondition>
                      <NodeBody>
                        <NodeList>
                          <Node NodeType="Command">
                            <NodeId>CD</NodeId>
                            <NodeBody>
                              <Command>
                                <Name>
                                  <StringValue>select_CD</StringValue>
                                </Name>
                              </Command>
                            </NodeBody>
                          </Node>
                        </NodeList>
                      </NodeBody>
                    </Node>
                  </NodeList>
                </NodeBody>
              </Node>
            </NodeList>
          </NodeBody>
        </Node>
        <Node NodeType="NodeList" FileName="DriveToSchool.ple" LineNo="182" ColNo="2">
          <NodeId>DriveUntilAtSchool</NodeId>
          <StartCondition>
            <AND>
              <EQInternal>
                <NodeStateVariable>
                  <NodeId>SelectStation</NodeId>
                </NodeStateVariable>
                <NodeStateValue>FINISHED</NodeStateValue>
              </EQInternal>
            </AND>
          </StartCondition>
          <NodeBody>
            <NodeList>
              <Node NodeType="NodeList">
                <NodeId>ep2cp_WhileBody</NodeId>
                <EndCondition>
                  <OR>
                    <EQInternal>
                      <NodeStateVariable>
                        <NodeId>ep2cp_WhileTrue</NodeId>
                      </NodeStateVariable>
                      <NodeStateValue>FINISHED</NodeStateValue>
                    </EQInternal>
                    <NOT>
                      <NOT>
                        <LookupNow>
                          <Name>
                            <StringValue>at_school</StringValue>
                          </Name>
                        </LookupNow>
                      </NOT>
                    </NOT>
                  </OR>
                </EndCondition>
                <NodeBody>
                  <NodeList>
                    <Node NodeType="NodeList">
                      <NodeId>ep2cp_WhileTrue</NodeId>
                      <StartCondition>
                        <NOT>
                          <LookupNow>
                            <Name>
                              <StringValue>at_school</StringValue>
                            </Name>
                          </LookupNow>
                        </NOT>
                      </StartCondition>
                      <RepeatCondition>
                        <NOT>
                          <LookupNow>
                            <Name>
                              <StringValue>at_school</StringValue>
                            </Name>
                          </LookupNow>
                        </NOT>
                      </RepeatCondition>
                      <NodeBody>
                        <NodeList>
                          <Node NodeType="Command">
                            <NodeId>DriveABit</NodeId>
                            <NodeBody>
                              <Command>
                                <Name>
                                  <StringValue>drive_a_bit</StringValue>
                                </Name>
                              </Command>
                            </NodeBody>
                          </Node>
                        </NodeList>
                      </NodeBody>
                    </Node>
                  </NodeList>
                </NodeBody>
              </Node>
            </NodeList>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
