<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Mon Jul  9 09:09:23 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="flag" type="bool">
      <Value>true</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
