/**
 * @file safe2ditch_msgids.h
 * @brief message definitions for safe2ditch app
 */

#ifndef ICAROUS_CFS_SAFE2DITCH_MSGIDS_H
#define ICAROUS_CFS_SAFE2DITCH_MSGIDS_H

/**
 * @defgroup SAFE2DITCH_MESSAGE_TOPICS
 * @brief Message topics of software bus messages generated by the safe2ditch app
 * @ingroup TRAFFIC
 * @ingroup TOPICS
 * @{
 */

#define SAFE2DITCH_STATUS_MID 0x0010


#endif //ICAROUS_CFS_SAFE2DITCH_MSGIDS_H
