MACRO(get_subdirs result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    SET(full_path ${curdir}/${child})
    IF(IS_DIRECTORY ${full_path})
      LIST(APPEND dirlist ${full_path})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()