/*
 * Copyright (c) 2016 United States Government as represented by
 * the National Aeronautics and Space Administration.  No copyright
 * is claimed in the United States under Title 17, U.S.Code. All Other
 * Rights Reserved.
 */
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class FENCE_BREACH {
   public static final int FENCE_BREACH_NONE = 0; /* No last fence breach | */
   public static final int FENCE_BREACH_MINALT = 1; /* Breached minimum altitude | */
   public static final int FENCE_BREACH_MAXALT = 2; /* Breached maximum altitude | */
   public static final int FENCE_BREACH_BOUNDARY = 3; /* Breached fence boundary | */
   public static final int FENCE_BREACH_ENUM_END = 4; /*  | */
}
            