/*
 * Copyright (c) 2016 United States Government as represented by
 * the National Aeronautics and Space Administration.  No copyright
 * is claimed in the United States under Title 17, U.S.Code. All Other
 * Rights Reserved.
 */
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Enumeration of landed detector states
*/
public class MAV_LANDED_STATE {
   public static final int MAV_LANDED_STATE_UNDEFINED = 0; /* MAV landed state is unknown | */
   public static final int MAV_LANDED_STATE_ON_GROUND = 1; /* MAV is landed (on ground) | */
   public static final int MAV_LANDED_STATE_IN_AIR = 2; /* MAV is in air | */
   public static final int MAV_LANDED_STATE_ENUM_END = 3; /*  | */
}
            