/*
 * Copyright (c) 2016 United States Government as represented by
 * the National Aeronautics and Space Administration.  No copyright
 * is claimed in the United States under Title 17, U.S.Code. All Other
 * Rights Reserved.
 */
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Bitmask of options for the MAV_CMD_DO_REPOSITION
*/
public class MAV_DO_REPOSITION_FLAGS {
   public static final int MAV_DO_REPOSITION_FLAGS_CHANGE_MODE = 1; /* The aircraft should immediately transition into guided. This should not be set for follow me applications | */
   public static final int MAV_DO_REPOSITION_FLAGS_ENUM_END = 2; /*  | */
}
            